export { MainSection } from './ui/Main/Main'
export { ServicesSection } from './ui/Services/Services'
export { ProcessSection } from './ui/Process/Process'
export { TeamSection } from './ui/Team/Team'
export { ReviewsSection } from './ui/Reviews/Reviews'
export { ContactUsSection } from './ui/ContactUs/ContactUs'
